In [35]:
%run ../base_setup.ipynb

DTU: 1.07.018
DBU: 1.00.029

In [36]:
tr = Transition('opportunities-many')
db = DataBuilder("opportunities-many")
tools = db.tools

In [37]:
tr_accounts = Transition('accounts-many')
df = tr_accounts.get_source_data()
sample_size = df.shape[0]

In [38]:
df_names = tools.get_profiles(size = 10000, mf_weighting=[7,3], seed = 1)

associate = [{'gender': {'expect': 'category','value': ['M', 'F']}}]
actions = {0: {'action': 'get_custom', 'kwargs' : {'code_str': "f'{first_name} {last_name}'", 'first_name': {'_header': 'forename'},'last_name': {'_header': 'surname'}}}}
df_names['SponsorName']= tools.associate_dataset(df_names, associations=associate, actions=actions)

In [55]:
tr.discover.data_dictionary(df_names)

,Attribute,Type,% Nulls,Count,Unique,Observations
0,SponsorName,object,0.0,100000000,10000,Sample: Dana Gremmels | Ibrahim Lohrmann | Steve Poirot
1,forename,object,0.0,100000000,4147,Sample: Natasha | Fred | Murray
2,gender,object,0.0,100000000,2,Sample: M | F
3,surname,object,0.0,100000000,10000,Sample: Liebenow | Couturier | Lowenstein

In [41]:
df_names = pd.DataFrame(np.repeat(df_names.values,100,axis=0), columns=df_names.columns)

In [53]:
sponsor_selection = df_names['SponsorName']
sponsor_weighting = [2,5,3,4,3,4,7,8.4,10]
df['Sponsor'] = tools.get_category(selection = sponsor_selection, weight_pattern=sponsor_weighting, size = sample_size)

In [54]:
df.head()

,state_s,company,metro,city,industry,state_l,website,Account_Id,Sponsor,Opportunity_Id
0,CA,Skillz,San Francisco,San Francisco,Software,California,http://skillz.com,0010E90980h8u91lDvP,None,0068P86287c1u54uFhD
1,CA,Skillz-1,San Francisco,San Francisco,Software,California,http://skillz.com,0012K85226u7u59uIuE,None,0068Z38805t9u95xGaU
2,CA,Skillz-2,San Francisco,San Francisco,Software,California,http://skillz.com,0014K06151k0u44mXnQ,None,0067F18782j7u77zIeS
3,CA,Skillz-3,San Francisco,San Francisco,Software,California,http://skillz.com,0013O36632b3u18aCzG,None,0063O66098e7u00hMpR
4,CA,Skillz-4,San Francisco,San Francisco,Software,California,http://skillz.com,0017W46951i4u86eTqL,None,0069D40919p1u41iCmU

In [48]:
df.shape

(1000000, 9)

In [49]:
df['Opportunity_Id'] = tools.get_string_pattern('006dUdddddlduddlUlU',choice_only=False, size = sample_size, seed = 1)

In [50]:
tr.discover.data_dictionary(df)

,Attribute,Type,% Nulls,Count,Unique,Observations
0,Account_Id,object,0.0,1000000,1000000,Sample: 0013E84815l0u92yMkT | 0019R25821n2u95jAvF | 0012T23433c0u53yIgT
1,Opportunity_Id,object,0.0,1000000,1000000,Sample: 0063S04846a1u92sYoI | 0063S50594t2u88iOaI | 0069N77209t0u60aNdN
2,Sponsor,object,1.0,0,0,Sample: Null Values
3,city,object,0.0,1000000,1408,Sample: Schnecksville | Folsom | Charlestown
4,company,object,0.0,1000000,1000000,Sample: Premier Auto Management-5 | Tapestry Technologies-11 | Be The C...
5,industry,object,0.0,999000,25,Sample: Security | Travel & Hospitality | Energy
6,metro,object,0.0,997800,303,"Sample: Binghamton, NY | Canton-Massillon, OH | Elkhart-Goshen, IN"
7,state_l,object,0.0,1000000,52,Sample: Nebraska | Idaho | Kentucky
8,state_s,object,0.0,1000000,52,Sample: GA | AZ | OH
9,website,object,0.0,999400,4995,Sample: filterworksusa.com | iofficecorp.com | riversedgecountertops.com

In [247]:
opportunity_selections = ["Engage - QuickStart(Customer360)" , "Engage - Enterprise(Conversational AI)", "Engage - Enterprise(Customer360)" , "Engage - QuickStart(Coversational AI)","Amplify - QuickStart(Process Insights)" , "Amplify - Enterprise(Process Insights)" , "Amplify - QuickStart(Survellance Insights)", "Amplify - Enterprise(Survellance Insights)", "Cortex QuickStart(MachineLearning)", "Cortex QuickStart(AI Develpoment)","Cortex Enterprise(MachineLearning)", "Cortex Enterprise(AI Develpoment)"] 
opportunity_weighting = [4,1,1,3,3,1,1,4,3,3,1,2]
df['Opportunity_Name'] = tools.get_category(selection = opportunity_selections, weight_pattern=opportunity_weighting, size = sample_size, seed = 1)

In [248]:
status_selection = ['Proposed Solution','Prospecting','Confirming Value with Power','Use Case Confirmed', 'Needs Identification', 'Negotiations']
status_weighting = [2,5,1,3,3,4]
df['Status'] = tools.get_category(selection = status_selection, weight_pattern=status_weighting, size = sample_size, seed = 1)

In [249]:
date_weighting = list(np.exp(np.arange(-5, 0.0, 0.2)).round(2))+[1,2,5,10,11,10,9,8,5]
until = datetime.datetime.today()
start = until - pd.DateOffset(years = 2)

df['LastModifiedDate'] = tools.get_datetime(start= start, until= until, date_pattern=date_weighting, date_format= '%Y-%m-%d %H:%M:%S' , size=sample_size, seed = 1)

In [250]:
opportunity_correlation = [["Engage - QuickStart(Customer360)" ,"Engage - QuickStart(Coversational AI)","Amplify - QuickStart(Process Insights)", "Amplify - QuickStart(Survellance Insights)",  "Cortex QuickStart(MachineLearning)", "Cortex QuickStart(AI Develpoment)"],[ "Engage - Enterprise(Coversational AI)", "Engage - Enterprise(Customer360)" , "Amplify - Enterprise(Process Insights)", "Amplify - Enterprise(Process Insights)", "Amplify - Enterprise(Survellance Insights)","Cortex Enterprise(MachineLearning)", "Cortex Enterprise(AI Develpoment)" ]] 
opportunity_action = {0: {'action': 50000}, 
                      1: {'action': 'get_number', 'kwargs' : {'from_value':100, 'to_value' : 50000, 'weight_pattern': [1,3,5,4,3,1]+[1]*5, 'offset': 1000}}}
df['Amount'] = tools.correlate_categories(df['Opportunity_Name'], correlations = opportunity_correlation, actions= opportunity_action, value_type= "category" )

In [251]:
# df_names_contacts = tools.get_profiles(size = sample_size, mf_weighting=[7,3])

# associate = [{'gender': {'expect': 'category','value': ['M', 'F']}}]
# actions = {0: {'action': 'get_custom', 'kwargs' : {'code_str': "f'{first_name} {last_name}'", 'first_name': {'_header': 'forename'},'last_name': {'_header': 'surname'}}}}
# df['ContactName']= tools.associate_dataset(df_names_contacts, associations=associate, actions=actions)

In [252]:
df.head()

,Sector,City,Industry,title,State,Account_Id,Sponsor,Opportunity_Id,Opportunity_Name,Status,LastModifiedDate,Amount
0,Retailing,Bentonville,General Merchandisers,Walmart,AR,0015I11484m7u87wBuD,Rosella Hymer,0068P86287c1u54uFhD,Amplify - QuickStart(Process Insights),Confirming Value with Power,2019-03-04 16:20:56,50000
1,Energy,Irving,Petroleum Refining,Exxon Mobil,TX,0017K23751y0u72fZpZ,Astrid Schmaus,0068Z38805t9u95xGaU,Amplify - Enterprise(Survellance Insights),Use Case Confirmed,2019-05-04 15:18:01,10580000
2,Financials,Omaha,Insurance: Property and Casualty (Stock),Berkshire Hathaway,NE,0017O90702b2u22mRuO,Janice Cerniglia,0067F18782j7u77zIeS,Cortex Enterprise(AI Develpoment),Negotiations,2019-01-24 05:32:38,21483000
3,Technology,Cupertino,"Computers, Office Equipment",Apple,CA,0014B28932p5u37rWgX,Paris Poma,0063O66098e7u00hMpR,Engage - Enterprise(Customer360),Prospecting,2019-04-08 13:06:42,10089000
4,Health Care,Minnetonka,Health Care: Insurance and Managed Care,UnitedHealth Group,MN,0015R72262j6u33kWxP,Lisa Kalafatis,0069D40919p1u41iCmU,Cortex Enterprise(MachineLearning),Negotiations,2018-11-18 20:51:03,9141000

In [253]:
# contact_title_selections = ["Vice Presitdent-Sales" , "Sr Data Scientist", "SVP Decision Sciences",  "VP", "ML Engineer","CEO"] 
# contact_title_weighting = [3,4,3,2,5,1]
# df['ContactTitle'] = tools.get_category(selection = contact_title_selections, weight_pattern=contact_title_weighting, size = sample_size)

In [254]:
df = df.rename(index=str, columns={"title": "AccountName"})

In [255]:
df2 = pd.read_csv("../../data/0_raw/contacts.csv")
df2 = df2.rename(index=str, columns={"Company Name": "AccountName", "Employee Title" : "ContactTitle"})
df2["ContactName"] = df2["Employee First Name"]+ " " +df2["Employee Last Name"]
df2 = df2.drop(columns = ['Employee First Name', 'Employee Last Name'])
df2 = df2.drop_duplicates(["AccountName"])

In [256]:
df = pd.merge(df,df2, on='AccountName', how= 'left')

In [257]:
analysis = discover.analyse_category(df['ContactName'])
size = len(df['ContactName'][df['ContactName'].isna()])
df_names = tools.get_profiles(size = size, mf_weighting=[6,4], seed = 1)
associate = [{'gender': {'expect': 'category','value': ['M', 'F']}}]
actions = {0: {'action': 'get_custom', 'kwargs' : {'code_str': "f'{first_name} {last_name}'", 'first_name': {'_header': 'forename'},'last_name': {'_header': 'surname'}}}}
df_names= tools.associate_dataset(df_names, associations=associate, actions=actions)
df['ContactName'][df['ContactName'].isna()] = df_names

In [258]:
df['ContactEmail'] = df["ContactName"].str.lower().str.replace(' ', '')+ "@"+ df['AccountName'].str.lower().str.replace(' ', '')+ ".com"

In [259]:
# associations = [{'ContactName': {'expect': 'category', 'value': [None]}}
#                  ,
#                 {'ContactName': {'expect': 'category', 'value':filter(None,df['ContactName'].tolist())}}]

# actions = {0: {'action': None},
#            1: {'action': 'get_string_pattern','kwargs' : {'choice_only': False}}}
# df['phone'] = tools.associate_dataset(df, associations=associations, actions=actions)

In [260]:
# import numpy as np
# df['Phone'] = np.where(df['ContactName'].isnull(), df['ContactName'], df['Phone'])

In [261]:
phone_correlation = discover.analyse_category(df['ContactName']).get('selection')
df['Phone'] = tools.get_string_pattern(pattern = "(5dd)ddd-dddd", choice_only=False, seed = 1, size=sample_size)

In [262]:
tr.discover.data_dictionary(df)

,Attribute,Type,% Nulls,Count,Unique,Observations
0,AccountName,object,0.0,75,75,Sample: Pfizer | IBM | Humana
1,Account_Id,object,0.0,75,75,Sample: 0010D33191a5u93sToX | 0010L37087k8u42oBoT | 0015J86713p3u81hWqK
2,Amount,object,0.0,75,25,Sample: 30194000 | 2127000 | 47280000
3,City,object,0.0,75,57,Sample: Detroit | Louisville | Fort Worth
4,ContactEmail,object,0.0,75,75,Sample: dougfries@citigroup.com | lillyraymo@statefarminsurancecos..com...
5,ContactName,object,0.0,75,68,Sample: Michael Solien | Jayne Knox | Jerome Ijames
6,ContactTitle,object,0.4,45,39,Sample: Executive VP & Chief Information Officer (Future Retirement SOM...
7,Industry,object,0.0,75,35,"Sample: Insurance: Life, Health (stock) | Internet Services and Retaili..."
8,LastModifiedDate,object,0.0,75,75,Sample: 2019-01-16 16:29:01 | 2018-12-08 06:54:37 | 2019-04-01 23:29:23
9,Opportunity_Id,object,0.0,75,75,Sample: 0069E01901i9u08wEtQ | 0062H40874p6u33iLvB | 0069P71098l8u89xMxY
10,Opportunity_Name,object,0.0,75,12,Sample: Cortex QuickStart(MachineLearning) | Amplify - QuickStart(Proce...
11,Phone,object,0.0,75,75,Sample: (519)654-3529 | (536)896-8793 | (583)557-5808
12,Sector,object,0.0,75,16,Sample: Technology | Wholesalers | Household Products
13,Sponsor,object,0.0,75,26,Sample: Ignacio Volkens | Lane Peoples | Paris Poma
14,State,object,0.0,75,25,Sample: TX | Michigan | RI
15,Status,object,0.0,75,6,Sample: Negotiations | Confirming Value with Power | Needs Identification

In [263]:
df.head(10)

,Sector,City,Industry,AccountName,State,Account_Id,Sponsor,Opportunity_Id,Opportunity_Name,Status,LastModifiedDate,Amount,ContactTitle,ContactName,ContactEmail,Phone
0,Retailing,Bentonville,General Merchandisers,Walmart,AR,0015I11484m7u87wBuD,Rosella Hymer,0068P86287c1u54uFhD,Amplify - QuickStart(Process Insights),Confirming Value with Power,2019-03-04 16:20:56,50000,Chief Information Officer (Walmart Brazil),Eduardo Brayner,eduardobrayner@walmart.com,(588)628-7215
1,Energy,Irving,Petroleum Refining,Exxon Mobil,TX,0017K23751y0u72fZpZ,Astrid Schmaus,0068Z38805t9u95xGaU,Amplify - Enterprise(Survellance Insights),Use Case Confirmed,2019-05-04 15:18:01,10580000,NaN,Ridwan Zurawik,ridwanzurawik@exxonmobil.com,(589)388-0539
2,Financials,Omaha,Insurance: Property and Casualty (Stock),Berkshire Hathaway,NE,0017O90702b2u22mRuO,Janice Cerniglia,0067F18782j7u77zIeS,Cortex Enterprise(AI Develpoment),Negotiations,2019-01-24 05:32:38,21483000,NaN,Courtney Bodey,courtneybodey@berkshirehathaway.com,(575)187-8297
3,Technology,Cupertino,"Computers, Office Equipment",Apple,CA,0014B28932p5u37rWgX,Paris Poma,0063O66098e7u00hMpR,Engage - Enterprise(Customer360),Prospecting,2019-04-08 13:06:42,10089000,NaN,Axel Whitsel,axelwhitsel@apple.com,(536)609-8470
4,Health Care,Minnetonka,Health Care: Insurance and Managed Care,UnitedHealth Group,MN,0015R72262j6u33kWxP,Lisa Kalafatis,0069D40919p1u41iCmU,Cortex Enterprise(MachineLearning),Negotiations,2018-11-18 20:51:03,9141000,Chief Information Officer (UnitedHealth Group) & Executive VP (Optum Te...,John Santelli,johnsantelli@unitedhealthgroup.com,(593)409-1914
5,Wholesalers,SF,Wholesalers: Health Care,McKesson,CA,0014X88750f8u17sOyN,Paris Poma,0064Z63377z7u89oKiH,Engage - QuickStart(Customer360),Proposed Solution,2019-04-22 05:06:05,50000,Chief Information Officer (McKesson Specialty Health),John Venable,johnvenable@mckesson.com,(549)633-7797
6,Health Care,Woonsocket,Health Care: Pharmacy and Other Services,CVS Health,RI,0011D78566r2u35lZmG,Jayne Knox,0063U19583i0u51tKmN,Cortex QuickStart(AI Develpoment),Negotiations,2018-04-12 04:39:54,50000,NaN,Martha Cocks,marthacocks@cvshealth.com,(534)195-8380
7,Retailing,Seattle,Internet Services and Retailing,Amazon.com,WA,0016H55187a0u64bXlC,Freddie Faustman,0065W86164i1u85bAoY,Engage - QuickStart(Customer360),Proposed Solution,2019-03-11 09:25:00,50000,NaN,Erick Pezley,erickpezley@amazon.com.com,(556)861-6481
8,Telecommunications,Dallas,Telecommunications,AT&T,TX,0014A89474o7u08gAxF,Freddie Faustman,0069E01901i9u08wEtQ,Cortex QuickStart(MachineLearning),Needs Identification,2018-12-15 11:35:17,50000,"Director, Acting CIO (AT&T Government Solutions)",Ron Yttri,ronyttri@at&t.com,(594)019-0189
9,Motor Vehicles & Parts,Detroit,Motor Vehicles and Parts,General Motors,MI,0012V01205p4u70wXrX,Rosella Hymer,0069Q17172y0u04cMbK,Engage - Enterprise(Conversational AI),Prospecting,2018-12-30 22:53:49,Engage - Enterprise(Conversational AI),"Global Chief Information Officer, Cadillac",Lesley Ma,lesleyma@generalmotors.com,(590)171-7280

In [264]:
db.save_to_disk(df,filename="sfdc_accounts_opportunities.csv",file_format="csv",path='../../data/0_raw/' )

In [51]:
tools.get_category?

Signature: tools.get_category(selection: list, weight_pattern: list = None, quantity: float = None, size: int = None, at_most: int = None, seed: int = None)
Docstring:
returns a category from a list. Of particular not is the at_least parameter that allows you to
control the number of times a selection can be chocen.

:param selection: a list of items to select from
:param weight_pattern: a weighting pattern that does not have to add to 1
:param quantity: a number between 0 and 1 representing the percentage quantity of the data
:param size: an optional size of the return. default to 1
:param at_most: the most times a selection should be chocen
:param seed: a seed value for the random function: default to None
:return: an item or list of items chosen from the list
File:      ~/miniconda3/lib/python3.7/site-packages/ds_behavioral/generator/data_builder.py
Type:      function